# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('tran_name', models.CharField(max_length=30, verbose_name='快递名字')),
                ('tran_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='价格')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
