# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': '快递', 'verbose_name_plural': '快递'},
        ),
    ]
