# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181128_1516'),
        ('user', '0009_auto_20181128_1621'),
        ('order', '0002_auto_20181130_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderinfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('order_num', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('order_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='订单金额')),
                ('order_name', models.CharField(max_length=20, verbose_name='收货人名字')),
                ('recei_tel', models.CharField(max_length=11, verbose_name='收货人电话')),
                ('order_address', models.CharField(max_length=255, verbose_name='订单地址')),
                ('order_status', models.SmallIntegerField(choices=[[1, '代付款'], [2, '已付款'], [3, '代发货'], [4, '已收货'], [5, '待评价'], [6, '已评价'], [7, '待退货'], [8, '已退货'], [9, '取消订单']], default=1, verbose_name='订单状态')),
                ('show_money', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='实付金额')),
            ],
            options={
                'verbose_name': '订单信息表',
                'verbose_name_plural': '订单信息表',
            },
        ),
        migrations.CreateModel(
            name='Ordersku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('order_count', models.IntegerField(verbose_name='订单的数量')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='订单的价格')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Orderinfor', verbose_name='订单ID')),
                ('shop_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop_sku', verbose_name='订单商品的skuid')),
            ],
            options={
                'verbose_name': '订单商品管理',
                'verbose_name_plural': '订单商品管理',
            },
        ),
        migrations.CreateModel(
            name='Paymoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('pay_name', models.CharField(max_length=50, verbose_name='支付方式')),
                ('pay_logo', models.ImageField(upload_to='pay', verbose_name='图片')),
            ],
            options={
                'verbose_name': '支付方式管理',
                'verbose_name_plural': '支付方式管理',
            },
        ),
        migrations.AddField(
            model_name='orderinfor',
            name='pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Paymoney', verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='orderinfor',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Transport', verbose_name='运输方式'),
        ),
        migrations.AddField(
            model_name='orderinfor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id'),
        ),
    ]
