# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_infor',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='假删除'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='假删除'),
        ),
        migrations.AlterField(
            model_name='my_infor',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建'),
        ),
        migrations.AlterField(
            model_name='my_infor',
            name='my_address',
            field=models.CharField(max_length=50, verbose_name='用户地址'),
        ),
        migrations.AlterField(
            model_name='my_infor',
            name='my_data',
            field=models.DateField(blank=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='my_infor',
            name='my_from',
            field=models.CharField(blank=True, max_length=50, verbose_name='用户家乡'),
        ),
        migrations.AlterField(
            model_name='my_infor',
            name='my_name',
            field=models.CharField(max_length=11, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='my_infor',
            name='my_school',
            field=models.CharField(max_length=10, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='my_infor',
            name='my_tel',
            field=models.CharField(max_length=11, verbose_name='用户电话'),
        ),
        migrations.AlterField(
            model_name='my_infor',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='用户性别'),
        ),
        migrations.AlterField(
            model_name='my_infor',
            name='update_time',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='my_infor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='关联用户注册表'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=11, verbose_name='用户名'),
        ),
    ]
