# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181120_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_infor',
            name='user_img',
            field=models.ImageField(default='imges/infortx.png', upload_to='booktest', verbose_name='头像'),
        ),
    ]
