# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_my_infor_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_infor',
            name='user_img',
            field=models.ImageField(default='images/infortx.png', upload_to='booktest', verbose_name='头像'),
        ),
    ]
