# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='infor',
        ),
    ]
