# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 08:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181128_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='add_tel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机格式错误')], verbose_name='收货电话'),
        ),
    ]
