# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
            ],
            options={
                'verbose_name': '活动商品',
                'verbose_name_plural': '活动商品',
            },
        ),
        migrations.CreateModel(
            name='Active_zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('zone', models.CharField(max_length=50, verbose_name='活动专区名')),
                ('zone_contend', models.CharField(max_length=255, verbose_name='活动描述')),
                ('zone_order', models.ImageField(upload_to='', verbose_name='排序')),
                ('zone_sj', models.BooleanField(choices=[(1, '上架'), (2, '下架')], default=False, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '活动专区',
                'verbose_name_plural': '活动专区',
            },
        ),
        migrations.CreateModel(
            name='Index_active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('active', models.CharField(max_length=50, verbose_name='活动名')),
                ('active_img', models.ImageField(upload_to='shop_active', verbose_name='活动图片')),
                ('active_url', models.URLField()),
            ],
            options={
                'verbose_name': '首页活动',
                'verbose_name_plural': '首页活动',
            },
        ),
        migrations.CreateModel(
            name='Index_lunbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('pic_name', models.CharField(max_length=20, verbose_name='轮播名字')),
                ('pic', models.ImageField(default='images/banner.png', upload_to='shopbook', verbose_name='轮播图片')),
                ('pic_url', models.URLField(verbose_name='点击图片跳转的地址')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Shop_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('img_url', models.ImageField(upload_to='shop', verbose_name='图片')),
            ],
            options={
                'verbose_name': '商品相册',
                'verbose_name_plural': '商品相册',
            },
        ),
        migrations.CreateModel(
            name='Shop_sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('sku_name', models.CharField(max_length=50, verbose_name='商品名')),
                ('sku_intro', models.CharField(max_length=255, verbose_name='商品简介')),
                ('sku_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='价格')),
                ('sku_stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sku_sale', models.IntegerField(default=0, verbose_name='销量')),
                ('sku_logo', models.ImageField(upload_to='shop_sku', verbose_name='商品logo')),
                ('sku_sj', models.BooleanField(choices=[(1, '上架'), (2, '下架')], default=False, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': 'sku商品详情',
                'verbose_name_plural': 'sku商品详情',
            },
        ),
        migrations.CreateModel(
            name='Shop_sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('sort_name', models.CharField(max_length=50, verbose_name='分类名')),
                ('sort_intro', models.CharField(max_length=50, verbose_name='分类简介')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='Shop_spu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('spu_name', models.CharField(max_length=50, verbose_name='商品名')),
                ('spu_contend', models.CharField(max_length=255, verbose_name='内容')),
            ],
            options={
                'verbose_name': 'spu商品表',
                'verbose_name_plural': 'spu商品表',
            },
        ),
        migrations.CreateModel(
            name='Shop_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('unit', models.CharField(max_length=10, verbose_name='商品单位')),
            ],
            options={
                'verbose_name': '单位表',
                'verbose_name_plural': '单位表',
            },
        ),
        migrations.AddField(
            model_name='shop_sku',
            name='sort_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop_sort', verbose_name='分类id'),
        ),
        migrations.AddField(
            model_name='shop_sku',
            name='spu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop_spu', verbose_name='spu商品id'),
        ),
        migrations.AddField(
            model_name='shop_img',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop_sku', verbose_name='sku商品id'),
        ),
        migrations.AddField(
            model_name='active_shop',
            name='sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop_sku'),
        ),
        migrations.AddField(
            model_name='active_shop',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Active_zone'),
        ),
    ]
