# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181123_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_zone',
            name='zone_contend',
            field=models.TextField(verbose_name='活动描述'),
        ),
        migrations.AlterField(
            model_name='shop_sku',
            name='sku_intro',
            field=models.TextField(verbose_name='商品简介'),
        ),
        migrations.AlterField(
            model_name='shop_sort',
            name='sort_intro',
            field=models.TextField(verbose_name='分类简介'),
        ),
        migrations.AlterField(
            model_name='shop_spu',
            name='spu_contend',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
