# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181123_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_sku',
            name='sort_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop_unit', verbose_name='单位id'),
            preserve_default=False,
        ),
    ]
