# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_sku_sort_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_zone',
            name='zone_sj',
            field=models.BooleanField(choices=[(1, '上架'), (0, '下架')], default=False, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='shop_sku',
            name='sku_sj',
            field=models.BooleanField(choices=[(1, '上架'), (0, '下架')], default=False, verbose_name='是否上架'),
        ),
    ]
