# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181124_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_zone',
            name='zone_order',
            field=models.IntegerField(verbose_name='排序'),
        ),
    ]
