# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 07:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181125_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_zone',
            name='zone_contend',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='活动描述'),
        ),
        migrations.AlterField(
            model_name='shop_sort',
            name='sort_intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='分类简介'),
        ),
        migrations.AlterField(
            model_name='shop_spu',
            name='spu_contend',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容'),
        ),
    ]
