# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181119_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_infor',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1),
        ),
    ]
