# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181119_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_infor',
            name='my_data',
            field=models.DateField(default=1971),
            preserve_default=False,
        ),
    ]
